server:
  port: 8888
spring:
  application:
    name: vidal-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/thiagovidalpassos/vidal-microservices/tree/main/vidal-config-server
          username: thiagovidalpassos
          password: Tibia.159
          default-label: main
          search-paths:
          - 'greeting-service*'