server:
  port: 8888
spring:
  application:
    name: vidal-greeting-service
  config:
    import:
    - optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: qa
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
vidal-greeting-service:
  greeting: "Olá"
  default-value: "Mundo"